=== bojanVlasonjic/ScientificPublications/Schemas/document-revision.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="http://www.ftn.uns.ac.rs/scientific-publication"
  xmlns:rvw="http://www.ftn.uns.ac.rs/scientific-publication"
  xmlns:cmn="http://www.ftn.uns.ac.rs/common" xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
  jxb:version="2.0">
  <xs:import schemaLocation="common.xsd" namespace="http://www.ftn.uns.ac.rs/common"/>

  <xs:element name="document-revision">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="recommendation" type="rvw:TRecommendation"/>
        <xs:element name="questionare" type="rvw:TQuestionare"/>
        <xs:element name="comments-to-author" type="rvw:TComments"/>
        <xs:element name="comments-to-editor" type="rvw:TComments"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="TReviewHeader">
    <xs:sequence>
      <xs:element name="paper-id" type="xs:string">
      <xs:element name="reviewer-id" type="xs:string">
    </xs:sequence>
  </xs:simpleType>

  <xs:simpleType name="TRecommendation">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Accept"/>
      <xs:enumeration value="Reject"/>
      <xs:enumeration value="Minor Revisions"/>
      <xs:enumeration value="Major Revisions"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TQuestionare">
    <xs:sequence>
      <xs:element name="question" type="rvw:TQuestion" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TQuestion">
    <xs:sequence>
      <xs:element name="question-text" type="xs:string"/>
      <xs:element name="selected" type="rvw:TOption"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="TOption">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Strongly disagree"/>
      <xs:enumeration value="Disagree"/>
      <xs:enumeration value="Neutral"/>
      <xs:enumeration value="Agree"/>
      <xs:enumeration value="Strongly agree"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TComment">
    <xs:sequence>
        <xs:element name="referenced-text" type="xs:string"/>
        <xs:element name="comment" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TComments">
    <xs:sequence>
      <xs:element name="comment" maxOccurs="unbounded" type="rvw:TComment"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== bojanVlasonjic/ScientificPublications/Sample-documents/document-revision-instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<rvw:document-revision xmlns:cmn="http://www.ftn.uns.ac.rs/common"
 xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
 xmlns:rvw="http://www.ftn.uns.ac.rs/scientific-publication"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/scientific-publication file:/C:/Users/bojan/Desktop/SIIT/VII_semestar/XML-Projekat/ScientificPublications/Schemas/document-revision.xsd" id="50" paper-id="50">
    <rvw:recommendation>Accept</rvw:recommendation>
    <rvw:questionare>
        <rvw:question>
            <rvw:question-text>question-text0</rvw:question-text>
            <rvw:selected>Strongly disagree</rvw:selected>
        </rvw:question>
    </rvw:questionare>
    <rvw:comments-to-author>
        <rvw:comment>comment0</rvw:comment>
    </rvw:comments-to-author>
    <rvw:comments-to-editor>
        <rvw:comment>comment1</rvw:comment>
    </rvw:comments-to-editor>
</rvw:document-revision>
