=== bojanVlasonjic/ScientificPublications/Schemas/scientific-paper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/scientific-paper"
    xmlns:sp="http://www.ftn.uns.ac.rs/scientific-paper">
    
    <xs:element name="scientific-paper">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="header" type="sp:THeader"/>
                <xs:element name="abstract" type="sp:TAbstract"/>
                <xs:element name="sections" type="sp:TSections"/>
                <xs:element name="references" type="sp:TReferences"/>
            </xs:sequence>
            <xs:attribute name="received" type="xs:date"/>
            <xs:attribute name="revised" type="xs:date"/>
            <xs:attribute name="accepted" type="xs:date"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="university">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element ref="sp:address"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="address">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="city" type="xs:string"/>
                <xs:element minOccurs="0" name="state" type="xs:string"/>
                <xs:element name="country" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="THeader">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="authors" type="sp:TPaperAuthors"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType abstract="false" name="TAuthor">
        <xs:sequence>
            <xs:element minOccurs="1" name="first-name" type="xs:string"/>
            <xs:element minOccurs="0" name="middle-name" type="xs:string"/>
            <xs:element name="last-name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPaperAuthor">
        <xs:complexContent>
            <xs:extension base="sp:TAuthor">
                <xs:sequence>
                    <xs:element ref="sp:university"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPaperAuthors">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="paper-author" type="sp:TPaperAuthor"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TRefAuthors">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="ref-author" type="sp:TAuthor"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAbstract">
        <xs:all>
            <xs:element name="keywords" type="xs:string"/>
            <xs:element name="purpose" maxOccurs="1" type="sp:TParagraph"/>
            <xs:element minOccurs="0" name="paper-type" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="TSections">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="section" type="sp:TSection"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TSection">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="paragraph" nillable="false" type="sp:TParagraph"
            />
        </xs:sequence>
        <xs:attribute name="heading" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="TReferences">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="reference" nillable="false" type="sp:TReference"
            />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TReference">
        <xs:sequence>
            <xs:element name="authors" type="sp:TRefAuthors"/>
            <xs:element name="year" type="xs:nonNegativeInteger"/>
            <xs:element name="paper-name" type="xs:string"/>
            <xs:element name="journal" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="TParagraph">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element maxOccurs="1" minOccurs="0" name="bold" type="xs:string"/>
            <xs:element maxOccurs="1" minOccurs="0" name="italic" type="xs:string"/>
            <xs:element minOccurs="0" name="underline" type="xs:string"/>
            <xs:element minOccurs="0" name="quote" type="xs:string"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== bojanVlasonjic/ScientificPublications/App/backend/data/instances/scientific-paper-instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<scientific-paper xmlns="http://www.ftn.uns.ac.rs/scientific-paper"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs ../Schemas/scientific-paper.xsd"
    received="2006-05-04" revised="2006-05-04" accepted="2006-05-04" id="1">
    <header>
        <title>title0</title>
        <authors>
            <author>
                <first-name>first-name0</first-name>
                <middle-name>middle-name0</middle-name>
                <last-name>last-name0</last-name>
                <institution>
                    <name>name0</name>
                    <location>
                        <city>city0</city>
                        <country>country0</country>
                    </location>
                </institution>
            </author>
            <author>
                <first-name>first-name1</first-name>
                <middle-name>middle-name1</middle-name>
                <last-name>last-name1</last-name>
                <institution>
                    <name>name1</name>
                    <location>
                        <city>city1</city>
                        <country>country1</country>
                    </location>
                </institution>
            </author>
        </authors>
    </header>
    <abstract>
        <keywords>keywords0</keywords>
        <purpose>
            <quote>quote0</quote>
            <underline>underline0</underline>
        </purpose>
        <paper-type>paper-type0</paper-type>
    </abstract>
    <sections>
        <section heading="heading1">
            <paragraph>
                <italic>italic0</italic>
                <bold>bold0</bold>
            </paragraph>
            <paragraph>
                <bold>bold1</bold>
                <quote>quote1</quote>
            </paragraph>
        </section>
        <section heading="heading3">
            <paragraph>
                <italic>italic1</italic>
                <bold>bold2</bold>
            </paragraph>
            <paragraph>
                <underline>underline1</underline>
                <underline>underline2</underline>
            </paragraph>
        </section>
    </sections>
    <references>
        <reference>
            <authors>
                <author>
                    <first-name>first-name2</first-name>
                    <middle-name>middle-name2</middle-name>
                    <last-name>last-name2</last-name>
                </author>
                <author>
                    <first-name>first-name3</first-name>
                    <middle-name>middle-name3</middle-name>
                    <last-name>last-name3</last-name>
                </author>
            </authors>
            <year>50</year>
            <paper-name>paper-name0</paper-name>
            <journal>journal0</journal>
        </reference>
    </references>
</scientific-paper>

=== bojanVlasonjic/ScientificPublications/App/backend/ScientificPublications/src/main/resources/data/xml_examples/scientific-paper-ee.xml
<?xml version="1.0" encoding="UTF-8"?>
<sp:scientific-paper xmlns:cmn="http://www.ftn.uns.ac.rs/common"
                     xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
                     xmlns:sp="http://www.ftn.uns.ac.rs/scientific-publication"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="http://www.ftn.uns.ac.rs/scientific-publication file:/C:/Users/bojan/Desktop/SIIT/VII_semestar/XML-Projekat/ScientificPublications/Schemas/scientific-paper.xsd">
    <sp:header>
        <sp:title>ELEKTRO</sp:title>
        <sp:authors>
            <cmn:author>
                <cmn:first-name>first-name1</cmn:first-name>
                <cmn:last-name>last-name1</cmn:last-name>
                <cmn:email>autor2@gmail.com</cmn:email>
                <cmn:institution>
                    <cmn:name>Faculty</cmn:name>
                    <cmn:location>
                        <cmn:city>City</cmn:city>
                        <cmn:country>Country</cmn:country>
                    </cmn:location>
                </cmn:institution>
            </cmn:author>
        </sp:authors>
    </sp:header>
    <sp:abstract>
        <sp:keywords>c, c++</sp:keywords>
        <sp:paper-type>type</sp:paper-type>
        <sp:purpose>
            blablabla
            <cmn:bold>blablalba</cmn:bold>
            <cmn:italic>blablalba</cmn:italic>
            blabla
        </sp:purpose>
    </sp:abstract>
    <sp:sections>
        <cmn:section>
            <cmn:header>header0</cmn:header>
            <cmn:paragraphs>
                <cmn:paragraph>
                    blablabla
                    <cmn:bold>blablalba</cmn:bold>
                    <cmn:italic>blablalba</cmn:italic>
                    blabla
                </cmn:paragraph>
            </cmn:paragraphs>
        </cmn:section>
    </sp:sections>
    <sp:references>
        <sp:reference>
            <sp:authors>
                <cmn:author>
                    <cmn:first-name>first-name1</cmn:first-name>
                    <cmn:last-name>last-name1</cmn:last-name>
                </cmn:author>
            </sp:authors>
            <sp:year>50</sp:year>
            <sp:paper-name>paper-name0</sp:paper-name>
        </sp:reference>
    </sp:references>
</sp:scientific-paper>

=== bojanVlasonjic/ScientificPublications/Sample-documents/scientific-paper-instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<sp:scientific-paper xmlns:sp="http://www.ftn.uns.ac.rs/scientific-publication"
 xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/scientific-publication file:/C:/Users/bojan/Desktop/SIIT/VII_semestar/XML-Projekat/ScientificPublications/Schemas/scientific-paper.xsd">
    <sp:header>
        <sp:title>title0</sp:title>
        <sp:authors>
            <sp:author>
                <sp:first-name>first-name0</sp:first-name>
                <sp:last-name>last-name0</sp:last-name>
            </sp:author>
        </sp:authors>
    </sp:header>
    <sp:abstract>
        <sp:keywords>keywords0</sp:keywords>
        <sp:purpose>
        </sp:purpose>
    </sp:abstract>
    <sp:sections>
        <sp:section>
            <sp:paragraph>
            </sp:paragraph>
        </sp:section>
    </sp:sections>
    <sp:references>
        <sp:reference>
            <sp:authors>
                <sp:author>
                    <sp:first-name>first-name1</sp:first-name>
                    <sp:last-name>last-name1</sp:last-name>
                </sp:author>
            </sp:authors>
            <sp:year>50</sp:year>
            <sp:paper-name>paper-name0</sp:paper-name>
        </sp:reference>
    </sp:references>
</sp:scientific-paper>
